<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-05-09 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2.11 on 2024-05-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 1158350472aa11fc8d7c6f11bb1947d57afb672e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Article',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('url_to_image', models.URLField()),
=======
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('source_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
>>>>>>> 1158350472aa11fc8d7c6f11bb1947d57afb672e
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeedapp.article')),
=======
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeedapp.headline')),
>>>>>>> 1158350472aa11fc8d7c6f11bb1947d57afb672e
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
