# Generated by Django 4.2.11 on 2024-05-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeedapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
