# Generated by Django 4.2.11 on 2024-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeedapp', '0002_alter_headline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
