# Generated by Django 4.2.11 on 2024-05-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeedapp', '0003_headline_category_headline_country_headline_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review',
        ),
    ]
